# Generated by Django 4.1.4 on 2022-12-22 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ProductCategory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Jacket and Sweater', 'Jacket and Sweater'), ('Tops', 'Tops'), ('T-shirt', 'T-shirt'), ('Pants', 'Pants'), ('All', 'All')], default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of Stock', 'Out of Stock')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
