# Generated by Django 4.1.4 on 2022-12-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_productcategory_remove_products_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('JACKET_AND_SWEATER', 'JACKET_AND_SWEATER'), ('TOPS', 'TOPS'), ('T-SHIRT', 'T-SHIRT'), ('PANTS', 'Pants'), ('ALL', 'ALL')], default='All', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.CharField(choices=[('IN_STOCK', 'IN_STOCK'), ('OUT_OF_STOCK', 'OUT_OF_STOCK')], default='', max_length=200),
        ),
    ]
