# Generated by Django 4.1.4 on 2023-01-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
