# Generated by Django 4.1.4 on 2023-01-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_order_user_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='Abc', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Abc', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(default='Abc', null=True),
        ),
    ]
