# Generated by Django 4.1.4 on 2023-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_order_username_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
