# Generated by Django 4.1.4 on 2023-01-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
