# Generated by Django 4.1.4 on 2023-01-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
